sudo: false

language: cpp

compiler:
#- gcc # the defualt gcc 4.6.x deos not support -std=c++11
- clang

before_script:
- mkdir build
- cd build
- cmake ..

script:
  - make

branches:
  only:
  - master

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

os:
- linux
- osx