sudo: true

language: cpp

compiler:
#- gcc # the defualt gcc 4.6.x deos not support -std=c++11
- clang

before_install:
- echo $LANG
- echo $LC_ALL

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

after_success:
  - cd ..
  - ./hello.sh

branches:
  only:
  - master

env:
  global:
    - LANG="en_US.UTF-8"
  matrix:
    - BUILD_TYPE=Debug
#    - BUILD_TYPE=Release

os:
  - linux