language: cpp

compiler:
- gcc
- clang

before_script: cmake CMakeLists.txt

script:
  - $CXX --version
  - make

branches:
  only:
  - master

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release